version: '2'

services:
  # Web server - For live reload and development
  # This environment can be used to run npm and node
  # commands as well
  dev:
    image: ambientum/node:8
    container_name: locadora-dev
    command: npm run dev
    volumes:
      - .:/var/www/app
    ports:
      - 8081:8080

  # Testing dist on a "real" webserver
  production:
    image: nginx:stable-alpine
    container_name: locadora-preview
    volumes:
      - ./dist:/usr/share/nginx/html
    ports:
      - 9090:80
